version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to docker
          command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Docker build
          command: docker build --rm=false -t ${DOCKER_USERNAME}/${IMAGE_NAME}:latest .
      - run:
          name: Push image to Dockerhub
          command: docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
workflows:
  version: 2
  build_docker:
    jobs:
      - build:
          filters:
            branches:
              only: master
